background = 0xFDF6E3FF
base = 0xFFF4F0D9
text = 0xFF5C6A72
alternate_base = 0xFFE0DCC7
bright_text = 0xFF5C6A72
accent = 0xFF3A94C5
link_text = 0xFF3A94C5
accent_secondary = 0xFF2A789F
font_family = "IBM Plex Mono"
font_family_monospace = "monospace"
font_size = 13
small_font_size = 10
rounding_large = 8
rounding_small = 4
